PACKAGE_NAME="yt9125"
PACKAGE_VERSION="1.1.008"
PROCS_NUM=`nproc`
[ $PROCS_NUM -gt 16 ] && PROCS_NUM=16

MAKE="cd make && 'make' -j$PROCS_NUM SDK_BASE_PATH=\$(pwd)/ LINUX_SRC_PATH=/lib/modules/\${kernelver}/build CPU_ARCH=arm64 Kernel_Mode=YES"
CLEAN="cd make && 'make' LINUX_SRC_PATH=/lib/modules/\${kernelver}/build CPU_ARCH=arm64 clean"

BUILT_MODULE_NAME[0]="yt9125"
BUILT_MODULE_LOCATION[0]="make/"
DEST_MODULE_LOCATION[0]="/updates"
AUTOINSTALL="yes"