PACKAGE_NAME="yt921x"
PACKAGE_VERSION="0.001.00"
PROCS_NUM=`nproc`
[ $PROCS_NUM -gt 16 ] && PROCS_NUM=16

MAKE="'make' -j$PROCS_NUM KVER=${kernelver}"
CLEAN="'make' KVER=${kernelver} clean"

BUILT_MODULE_NAME[0]="yt921x"
BUILT_MODULE_LOCATION[0]=""
DEST_MODULE_LOCATION[0]="/updates"

BUILT_MODULE_NAME[1]="tag_yt921x"
BUILT_MODULE_LOCATION[1]=""
DEST_MODULE_LOCATION[1]="/updates"

AUTOINSTALL="yes"
